### ISSUE TITLE
YCB数据集的测试问题

### ISSUE THREAD

**Issue by Bingo-1996** [ethnhe/FFB6D#10]
您好！
        请问您在论文中YCB数据集的测试结果是All object (following PoseCNN)还是Average of all object呢？
        我看到有些论文报告的平均值，有些论文报告的All值，请问这两种计算方式有什么区别吗？用哪个值更加fair呢？

        感谢您的解答

**Comment by ethnhe** [comment]
- 论文中的结果是和all object，和PoseCNN的结果保持一致。
- 平均值的算法是每个类别分别算出AUC然后再把所有类别的AUC取平均，All是所有类别的add-(s)合并起来算一个总的AUC。一般All会比Average难一些（结果偏低一些）。和别的方法比的时候用同一个指标，就是fair的。

**Comment by Bingo-1996** [comment]
好的，谢谢
