### ISSUE TITLE
Question about meanshift code

### ISSUE THREAD

**Issue by SnowdenLee** [ethnhe/FFB6D#12]
Hello,
I think the line here is a little problematic https://github.com/ethnhe/FFB6D/blob/c4b0da1fb6da916df51c71c0213c0557c0891230/ffb6d/utils/meanshift_pytorch.py#L173
I think it should be  Cr = **C**.view(N, 1, c).repeat(1, N, 1)
Could you please check it? Thank you!

**Comment by ethnhe** [comment]
A fixed one has been updated and support for multi clusters is also added. Use ```git pull``` to update your code.
