### ISSUE TITLE
how to input my own pictures?

### ISSUE THREAD

**Issue by robint-XNF** [ethnhe/FFB6D#16]
how could i use my own pictures and get the result? I couldn't find the Interface to change the pictures in demo.py.

**Comment by ethnhe** [comment]
You can modify the related dataset provider to read your own picture. The ```datasets/linemod/linemo_dataset.py``` for LineMOD dataset and the ```datasets/ycb/ycb_dataset.py``` for the YCB-Video dataset.

**Comment by nachi9211** [comment]
> You can modify the related dataset provider to read your own picture. The `datasets/linemod/linemo_dataset.py` for LineMOD dataset and the `datasets/ycb/ycb_dataset.py` for the YCB-Video dataset.

Hi Ethan,
In this case, how would I deal with the intrinsic matrix?

**Comment by weidu3** [comment]
Hello, do you implement the output of importing your own RGBD image into the model?
