### ISSUE TITLE
when i compile normalSpeed, there's an error.

### ISSUE THREAD

**Issue by TheRunningHorse** [ethnhe/FFB6D#17]
/home/vision/6d-pose-estimation/FFB6D/normalSpeed/normalSpeed/pybind11.cpp:7:16: error: expected constructor, destructor, or type conversion before ‘(’ token
 PYBIND11_MODULE(normalSpeed, m) {
                ^
CMakeFiles/normalSpeed.dir/build.make:89: recipe for target 'CMakeFiles/normalSpeed.dir/pybind11.cpp.o' failed

**Comment by TheRunningHorse** [comment]
I have installed pybind11.
sudo apt-get install pybind11-dev
sudo apt-get install python3-pybind11 
pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple/  pybind11

**Comment by TheRunningHorse** [comment]
it‘s ok now

**Comment by Gauravajariwal11** [comment]
Did you get any another error?
