### ISSUE TITLE
Wrong information when I installed the apex

### ISSUE THREAD

**Issue by Luan-Zhaoliang** [ethnhe/FFB6D#21]

**Comment by ethnhe** [comment]
It's an apex installation problem. Try to search for the solution or raise an issue in that project: [apex](https://github.com/NVIDIA/apex/issues).

**Comment by Luan-Zhaoliang** [comment]
> It's an apex installation problem. Try to search for the solution or raise an issue in that project: [apex](https://github.com/NVIDIA/apex/issues).

OK, thank you for your advice!
