### ISSUE TITLE
Pretrained Model on YCBV dataset

### ISSUE THREAD

**Issue by zhujunli1993** [ethnhe/FFB6D#22]
Hi,

I'm very interested in the demo. I'd like to know could you please upload the pretrained model(YCBV dataset)? Thank you so much! @ethnhe

**Comment by ethnhe** [comment]
We've released our pre-trained model on [onedrive](https://hkustconnect-my.sharepoint.com/personal/yhebk_connect_ust_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fyhebk%5Fconnect%5Fust%5Fhk%2FDocuments%2Fpublically%20shared%20%E5%85%B1%E4%BA%AB%E6%96%87%E4%BB%B6%E5%A4%B9%2FFFB6D%5Fpretrained%5Fmodels%2FYCB%5FVideo%2FFFB6D%5Fbest%2Epth%2Etar&parent=%2Fpersonal%2Fyhebk%5Fconnect%5Fust%5Fhk%2FDocuments%2Fpublically%20shared%20%E5%85%B1%E4%BA%AB%E6%96%87%E4%BB%B6%E5%A4%B9%2FFFB6D%5Fpretrained%5Fmodels%2FYCB%5FVideo&originalPath=aHR0cHM6Ly9oa3VzdGNvbm5lY3QtbXkuc2hhcmVwb2ludC5jb20vOnU6L2cvcGVyc29uYWwveWhlYmtfY29ubmVjdF91c3RfaGsvRVc3YTV3LXl0ZnRMZ2V4SXlYdUljandCNG8wZFdvMWhNdGVNTmxBMXpnTTdXZz9ydGltZT1Ma25Ya21kVjJVZw)
