### ISSUE TITLE
Wrong pred_cls_ids Results

### ISSUE THREAD

**Issue by zhujunli1993** [ethnhe/FFB6D#24]
Hi, 
I'm looking at demo.py codes, and when I ran it to test model's performance on ycbv dataset, I found the pretrained model couldn't segment objects correctly. For example, the GT object class ids should be [1, 4, 6, 19, 20], but the pred_cls_ids was [ 1  6  7  9 13 14 17 18 19 20 21]. I'd like to know how to solve this problem? Thank you!

**Comment by ethnhe** [comment]
Our segmentation branch is a kind of bottom-up method, which may lead to some false-positive results. There are some ways to filter out these false positives:
- If the objects types in the scene are known as in some manipulation tasks, you can only select the results of target classes.
- If not, ways to reject the false positives include:
  - Increase the threshold of the minimum number of object points [here](https://github.com/ethnhe/FFB6D/blob/d21c099ced0033c4590d16cb02c48c60c6de4648/ffb6d/utils/pvn3d_eval_utils_kpls.py#L118). That may also lead to missing of some heavily occluded objects or small objects that have little visible points.
  - Use the estimated object pose and mesh models to calculate loss with the scene point clouds and filter out objects with a designed threshold.
