### ISSUE TITLE
Using multiple GPU for training

### ISSUE THREAD

**Issue by aimatter** [ethnhe/FFB6D#25]
Hey guys,

first great work that you have done! Things are looking good and working fine.
To accelarate the training a bit, I would like to use multiple GPUs.
Unfortunately this can not be done with the current version of the code. Do you have an idea how to adapt the code into this direction? Currently I am getting this error:

> Traceback (most recent call last):                                                                                                                                                         
>   File "train_lm.py", line 696, in <module>
>     train()
>   File "train_lm.py", line 687, in train
>     clr_div=clr_div
>   File "train_lm.py", line 486, in train
>     _, loss, res = self.model_fn(self.model, batch, it=it)
>   File "train_lm.py", line 247, in model_fn
>     end_points['pred_rgbd_segs'], labels.view(-1)
>   File "/home/xxx/.conda/envs/FFB6D/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/xxx/Documents/FFB6D/ffb6d/models/loss.py", line 31, in forward
>     logpt = logpt.gather(1,target)
> RuntimeError: arguments are located on different GPUs at /pytorch/aten/src/THC/generic/THCTensorScatterGather.cu:13

Any ideas?
How long did it take to train 10,000 fused and 70,000 render images on the 2080? Or how many iterations per second did your setup perform?

**Comment by aimatter** [comment]
@community
How long did your training take for the whole dataset including real, fuses and rendered images?

**Comment by ethnhe** [comment]
- The original apex version of code should support multi-GPUs training and we recommend multi GPUs training.
- It takes about 16 hours to train on the full LineMOD dataset with 8 2080 Ti GPUs and 24 hours on the YCB-Video dataset.
