### ISSUE TITLE
error when install apex and compile normalSpeed

### ISSUE THREAD

**Issue by MinWang1997** [ethnhe/FFB6D#26]
Hi all,

I create a conda .yml file and another requirements.txt for creating conda environment because I followed the tutorial of my administrator of GPU cluster to use conda install at first and only use pip when the packages are not available on conda.

However, I got some errors when I install apex as the following:

<img width="1284" alt="apex install" src="https://user-images.githubusercontent.com/75472853/129385229-e61956c3-9a42-451c-8955-66b38180b2d1.png">

After that, I add apex into .yml file and install NormalSpeed but I got the same error as this [issue](https://github.com/ethnhe/FFB6D/issues/23).

Could you help me fix it?

These are my .yml and .txt files .
<img width="183" alt="conda_yml" src="https://user-images.githubusercontent.com/75472853/129385022-9a1ba619-c747-4955-9657-4fea337ffd8c.png">
<img width="198" alt="pip requrements" src="https://user-images.githubusercontent.com/75472853/129385024-6debd08c-6494-4184-8318-19485fa251fe.png">

Best,
Min

**Comment by ethnhe** [comment]
- For the apex installation problem please refer to the [apex project](https://github.com/NVIDIA/apex/issues), try to raise an issue or search for solutions in the past issues there. 
- For the NormalSpeed issue try to install opencv3 from the source code as mention in the issue.

**Comment by MinWang1997** [comment]
> * For the apex installation problem please refer to the [apex project](https://github.com/NVIDIA/apex/issues), try to raise an issue or search for solutions in the past issues there.

Hi Yisheng,
Thank you for your reply.
 I have already [raised an issue](https://github.com/NVIDIA/apex/issues/1142) and searched for solutions in the past issues for apex. Can I simply[ install apex by conda](https://anaconda.org/conda-forge/nvidia-apex)? 

The problem of NormalSpeed disappeared automatically when I install apex by conda.

**Comment by ethnhe** [comment]
Sorry that I didn't try to install apex by conda. You can have a try, see if it works well, and update the issue.

**Comment by MinWang1997** [comment]
> Sorry that I didn't try to install apex by conda. You can have a try, see if it works well, and update the issue.

No it shows the same error - lack of cpp extension.
I tried to install the latest torch version and installed apex successfully.

`conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`



```
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

and then install other packages...
