### ISSUE TITLE
关于训练次数的问题

### ISSUE THREAD

**Issue by ssswtshiwo** [ethnhe/FFB6D#27]
你好，请问如果想达到你提供的预训练模型的结果大概需要训练多少epoch呢, 谢谢！

**Comment by ethnhe** [comment]
通常模型再9-10 epochs的时候会有一个比较好的结果，最好的结果一般在18-21 epochs之间。

**Comment by Mr2er0** [comment]
你好，按照发布的代码训练出来的结果和文中的结果有0.4到0.5的差距。而且最好的模型是在最后的epoch出现的。是不是一些训练参数比如学习率之类的不是你最终的训练参数呢

**Comment by LEONHWH** [comment]
> 你好，按照发布的代码训练出来的结果和文中的结果有0.4到0.5的差距。而且最好的模型是在最后的epoch出现的。是不是一些训练参数比如学习率之类的不是你最终的训练参数呢

@ethnhe 我同样有这样的问题，貌似linemod的数据集上训练出的结果比较顺利，ycb的情况就十分复杂。

ycb数据集上我用Rtx2080 bz = 8x3的情况下训练了很多个epoch，结果都不尽人意。我在另一个服务器采用 RTX3090 bz  =2x9,并且稍微调低的学习率还能获得不错的结果。
