### ISSUE TITLE
default batch size and mini batch size 3

### ISSUE THREAD

**Issue by MinWang1997** [ethnhe/FFB6D#29]
Hi Yisheng,

I used default Configuration for training and just noticed that

>  If you use less than 8 GPU and the batch size is less than "3x8=24", it's recommended to use mixed precision trainning and increase the mini_batch_size in common.py as large as possible.

Could you tell me why you set baoth default batch size and mini-batch size to the same 3 instead of 2,4,8,..?

Best,
Min

**Comment by ethnhe** [comment]
We use 2080Ti and each GPU can only process a mini-batch size of 3 due to memory limitation. If you use GPUs with larger memory, you can increase that number.
