### ISSUE TITLE
undefined symbol: PyThread_tss_get

### ISSUE THREAD

**Issue by an99990** [ethnhe/FFB6D#30]
This issue comes from `sh demo_ycb.sh`
apex and normalSpeed were successfully installed.
full error message
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/halodi/test_2_venv/FFB6D/ffb6d/demo.py", line 19, in <module>
    from datasets.ycb.ycb_dataset import Dataset as YCB_Dataset
  File "/home/halodi/test_2_venv/FFB6D/ffb6d/datasets/ycb/ycb_dataset.py", line 11, in <module>
    from utils.basic_utils import Basic_Utils
  File "/home/halodi/test_2_venv/FFB6D/ffb6d/utils/basic_utils.py", line 9, in <module>
    import normalSpeed
ImportError: /home/halodi/.local/lib/python3.6/site-packages/normalSpeed-0.0.1-py3.6-linux-x86_64.egg/normalSpeed.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyThread_tss_get

```

**Comment by ethnhe** [comment]
It seems the normalSpeed problem. Check that normalSpeed is successfully installed by running the [example](https://github.com/hfutcgncas/normalSpeed#example) in that repo.

**Comment by an99990** [comment]
issue fixed in repo normalspeed

**Comment by Gauravajariwal11** [comment]
hey @an99990  I have the same error, how did you fix it?

**Comment by an99990** [comment]
Yu have to make sure you're using the right python version. I used python 3.8.
Call it by giving the full path of your python.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Gauravajariwal11** [comment]
I am using python 3.6.9. and calling it with the full path. Is there anything else that you tried?

**Comment by an99990** [comment]
Frim what I understood the error stops after you use a newer version of python you should try with python 3.8.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
