### ISSUE TITLE
How to run the code on the single GPU?

### ISSUE THREAD

**Issue by LZL-CS** [ethnhe/FFB6D#37]
Hi,

Thank you very much for your nice work!
I have a look at your code and your model run with 8 GPUs, but I have only one GPU, may I know how can modify the code to run the code?

Kind regards,

**Comment by cwkim1993** [comment]
You can train with single GPU by changing line in train_lm.sh file like below..
python -m torch.distributed.launch --nproc_per_node=1 train_lm.py --gpu "0" --gpus 1

**Comment by LZL-CS** [comment]
> You can train with single GPU by changing line in train_lm.sh file like below.. python -m torch.distributed.launch --nproc_per_node=1 train_lm.py --gpu "0" --gpus 1

Ok, I'll have a try, thanks for your reply!
