### ISSUE TITLE
Evaluation on physical YCB Objects

### ISSUE THREAD

**Issue by ghost** [ethnhe/FFB6D#60]
Hi,
Thank your very much for your work. As part of my studies, I am doing a semester project on FFB6D and I am focusing on the YCB Video Dataset. I have already downloaded and run the demo to see the visualisation results (using the pretrained model). It seems that I get the same results both quantitatively and qualitatively.
Now I need to gather a small lab dataset with physical YCB objects and evaluate the performance using FFB6D and an Intel Realsense d415/ Kinect Azure RGBD camera. 

- How do I need to process the pictures before using the demo ? In other words, what type of picture files (formats) do I need to provide to the code to run properly (an RGB image and a Depth Image only ?)
- Can we apply the code for real-time applications (images directly from the camera feed)  ? How to modify the code accordingly ?
- Does a ROS application exist (for instance having a robot manipulator grasp objects whose pose has been estimated with FFB6D) ?

Thank you very much for your feedback, it would greatly help.

**Comment by MiriamJo** [comment]
Can you tell me how this issue is closed? Did you figure it out? I'd also like to know. :-) 
I guess the paper does answer some of these questions, but in general papers do not apply well in "real world" scenarios, usaually.
