### ISSUE TITLE
"Bad" results with Realsense camera using the demo with real YCB objects

### ISSUE THREAD

**Issue by ghost** [ethnhe/FFB6D#66]
Hello @ethnhe ,

I am using your pretrained weights for the YCB dataset on my custom camera (Intel Realsense d415) stream/pictures but it seems that there is some kind of "shifting" applied to the objects (the orientation and size seem correct).
I have changed the K intrinsics and the factor depth to my camera.

Here you can see the best results I have managed to get for some objects but it's not accurate.

![image](https://user-images.githubusercontent.com/73893752/167441767-1310626e-ec05-40ff-848b-737f9d2044c3.png)

How can I improve the results? Do you have any suggestions? 

Thank you very much for your time and consideration.

**Comment by andreazuna89** [comment]
Dear @lucasbrd have you solved it? which modifications have you made in the demo code for running with your camera?

Thanks a lot
