### ISSUE TITLE
Setting up dataset with fused & rendered data

### ISSUE THREAD

**Issue by CandiceD17** [ethnhe/FFB6D#7]
While I trained this model with Linemod, I encountered the following warning:

Warning: Trainnig without fused data will hurt model performance 
Please generate fused data from https://github.com/ethnhe/raster_triangle.

I go to this github repo and compiled the rendered & fused data, but how can I incorporate these into the dataset  of FFB6D?
Thank you for your help~

**Comment by ethnhe** [comment]
Simply run the training scripts again and it works if the Warning disappears. 

Specifically, if you soft link the LineMOD dataset ```Linemod_preprocessed``` to ```raster_triangle/Linemod_preprocessed``` using ```ln -s path_to_Linemod_preprocessed ./Linemod_preprocessed``` following the README, the generate rendered & fused data will be in ```Linemod_preprocessed/renders``` and ```Linemod_preprocessed/fuse```. And If you soft link the same ```Linemod_preprocessed``` folder to ```ffb6d/datasets/linemod/Linemod_preprocessed```. The scripts ```linemod_dataset.py``` will find these generated data.
