### ISSUE TITLE
RandLa installation not found, even though installation was succesful

### ISSUE THREAD

**Issue by HannahHaensen** [ethnhe/FFB6D#77]
I use python 3.7

After installing everything according to the Installation instruction I get the following error when running `sh test_lm.sh`

`Traceback (most recent call last):
  File "train_lm.py", line 31, in <module>
    from models.ffb6d import FFB6D
  File "/home/user/Documents/GitHub/FFB6D_conda/ffb6d/models/ffb6d.py", line 6, in <module>
    from models.RandLA.RandLANet import Network as RandLANet
  File "/home/user/Documents/GitHub/FFB6D_conda/ffb6d/models/RandLA/RandLANet.py", line 5, in <module>
    from helper_tool import DataProcessing as DP
  File "/home/user/Documents/GitHub/FFB6D_conda/ffb6d/models/RandLA/helper_tool.py", line 15, in <module>
    import nearest_neighbors.lib.python.nearest_neighbors as nearest_neighbors
ModuleNotFoundError: No module named 'nearest_neighbors.lib.python.nearest_neighbors'
`

**Comment by HannahHaensen** [comment]
Also when clicking on nearest_neighbors in helper_tool-py

![image](https://user-images.githubusercontent.com/22636930/174756650-3e6604f2-9864-4e3c-9abf-76b279efdd19.png)

this opens but somehow nearest_neighbors.lib can not be resolved

structure of files:
![image](https://user-images.githubusercontent.com/22636930/174756943-1ed74af9-b7e9-4168-89f0-9605cd1ea0c5.png)

**Comment by HannahHaensen** [comment]
in helper_tool.py

I changed the import of cpp_wrapper and nearest_neighbors now at least this part seems to work correctly

```
import grid_subsampling as cpp_subsampling
import nearest_neighbors
```

**Comment by weidu3** [comment]
You can probably move the two files of the first picture out of the folder like the second picture.
![image](https://github.com/ethnhe/FFB6D/assets/101306990/31a3d8b7-9e60-44a3-a369-9d58c9249947)
![image](https://github.com/ethnhe/FFB6D/assets/101306990/ce80057c-1b06-4971-a47b-0c41254d9705)
